"""Stateful Pallas interpreter for batches of GPU2 GP programs.

Each Triton program evaluates one GP program over a block of grid points. JAX
0.5's Triton backend cannot lower the scatter generated by ``array.at[].set``
and does not expose Triton scratch allocations. The stack is therefore an
explicit stateful Pallas output buffer accessed with supported ``pl.load`` and
``pl.store`` operations. Writes are in-place, avoiding the large chains of
functional stack copies that caused the original GPU2 allocation failures.
"""

from __future__ import annotations

from functools import lru_cache

import jax
import jax.numpy as jnp
from jax.experimental import pallas as pl
from jax.experimental.pallas import triton as plgpu


DEFAULT_BLOCK_SIZE = 128


@lru_cache(maxsize=8)
def _batched_interpreter(
    max_program_nodes: int,
    max_constants: int,
    max_stack_depth: int,
    padded_point_count: int,
    block_size: int,
    interpret: bool,
):
    if padded_point_count % block_size:
        raise ValueError("Pallas point count must be a multiple of block_size")

    def kernel(
        opcodes_ref,
        operands_ref,
        literals_ref,
        n_ops_ref,
        parameters_ref,
        points_ref,
        output_ref,
        stack_ref,
    ):
        lane = jnp.arange(block_size, dtype=jnp.int32)

        def push_x(args):
            pointer, operand, _ = args
            value = pl.load(points_ref, (lane, operand))
            pl.store(stack_ref, (pointer, lane), value)
            return pointer + 1

        def push_parameter(args):
            pointer, operand, _ = args
            value = pl.load(parameters_ref, (operand,))
            pl.store(
                stack_ref,
                (pointer, lane),
                jnp.broadcast_to(value, (block_size,)),
            )
            return pointer + 1

        def push_literal(args):
            pointer, _, literal = args
            pl.store(
                stack_ref,
                (pointer, lane),
                jnp.broadcast_to(literal, (block_size,)),
            )
            return pointer + 1

        def binary(args, operation):
            pointer, _, _ = args
            left = pl.load(stack_ref, (pointer - 2, lane))
            right = pl.load(stack_ref, (pointer - 1, lane))
            pl.store(stack_ref, (pointer - 2, lane), operation(left, right))
            return pointer - 1

        def unary(args, operation):
            pointer, _, _ = args
            value = pl.load(stack_ref, (pointer - 1, lane))
            pl.store(stack_ref, (pointer - 1, lane), operation(value))
            return pointer

        branches = (
            push_x,
            push_parameter,
            push_literal,
            lambda args: binary(args, lambda x, y: x + y),
            lambda args: binary(args, lambda x, y: x - y),
            lambda args: binary(args, lambda x, y: x * y),
            lambda args: binary(
                args, lambda x, y: x / jnp.sqrt(1.0 + y * y)
            ),
            lambda args: unary(args, lambda x: -x),
            lambda args: unary(args, jnp.sin),
            lambda args: unary(args, jnp.exp),
        )

        def body(index, state):
            opcode = pl.load(opcodes_ref, (index,))
            operand = pl.load(operands_ref, (index,))
            literal = pl.load(literals_ref, (index,))
            return jax.lax.switch(
                opcode,
                branches,
                (state, operand, literal),
            )

        pointer = jax.lax.fori_loop(
            0,
            pl.load(n_ops_ref, ()),
            body,
            jnp.int32(0),
        )
        value = pl.load(stack_ref, (pointer - 1, lane))
        pl.store(output_ref, (lane,), value)

    single = pl.pallas_call(
        kernel,
        out_shape=(
            jax.ShapeDtypeStruct(
                (padded_point_count,), dtype=jnp.float64
            ),
            jax.ShapeDtypeStruct(
                (max_stack_depth, padded_point_count), dtype=jnp.float64
            ),
        ),
        grid=(padded_point_count // block_size,),
        in_specs=(
            pl.BlockSpec((max_program_nodes,), lambda _: (0,)),
            pl.BlockSpec((max_program_nodes,), lambda _: (0,)),
            pl.BlockSpec((max_program_nodes,), lambda _: (0,)),
            pl.BlockSpec((), lambda _: ()),
            pl.BlockSpec((max_constants,), lambda _: (0,)),
            pl.BlockSpec((block_size, 4), lambda block: (block, 0)),
        ),
        out_specs=(
            pl.BlockSpec((block_size,), lambda block: (block,)),
            pl.BlockSpec(
                (max_stack_depth, block_size), lambda block: (0, block)
            ),
        ),
        compiler_params=plgpu.TritonCompilerParams(num_warps=4, num_stages=1),
        interpret=interpret,
        name="gpu2_gp_register_interpreter",
    )

    # Pallas calls are vmappable: the leading dimension is a batch of
    # different programs and/or different constant vectors. The second output
    # is working storage and is intentionally discarded after the kernel.
    @jax.jit
    def evaluate(opcodes, operands, literals, n_ops, parameters, points):
        values, _ = jax.vmap(
            single, in_axes=(0, 0, 0, 0, 0, None)
        )(opcodes, operands, literals, n_ops, parameters, points)
        return values

    return evaluate


def evaluate_program_batch(
    opcodes,
    operands,
    literals,
    n_ops,
    parameters,
    points,
    *,
    max_stack_depth: int,
    block_size: int = DEFAULT_BLOCK_SIZE,
    interpret: bool = False,
):
    """Evaluate a batch of runtime programs at all padded ``points``."""
    evaluator = _batched_interpreter(
        int(opcodes.shape[1]),
        int(parameters.shape[1]),
        int(max_stack_depth),
        int(points.shape[0]),
        int(block_size),
        bool(interpret),
    )
    return evaluator(opcodes, operands, literals, n_ops, parameters, points)
